language: node_js
node_js:
  - "stable"

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"root",pwd:"__protected__",roles:["readWrite"]});'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

before_install:
  - npm install -g mocha
  - npm install 

script: 
  - npm test
  - npm run report-coverage

cache:
  directories:
    - "node_modules"